KakaoFunding/back-end

- src/main/java/org/kakaoshare/backend/common/config/QuerydslConfiguration.java
- src/main/java/org/kakaoshare/backend/domain/brand/dto/TabType.java
- src/main/java/org/kakaoshare/backend/domain/category/dto/CategoryDto.java
- src/main/java/org/kakaoshare/backend/domain/category/entity/Category.java
- src/main/java/org/kakaoshare/backend/domain/category/repository/CategoryRepository.java
- src/main/java/org/kakaoshare/backend/domain/category/repository/query/CategoryRepositoryCustom.java
- src/main/java/org/kakaoshare/backend/domain/category/repository/query/CategoryRepositoryCustomImpl.java
- src/main/java/org/kakaoshare/backend/domain/category/service/CategoryService.java
- src/test/java/org/kakaoshare/backend/domain/category/repository/CategoryRepositoryTest.java
- src/test/java/org/kakaoshare/backend/domain/category/service/CategoryServiceTest.java
close: #12 
카테고리 목록을 반환하는 로직을 작성했습니다.
- ~~추후에 client단에서 카테고리의 ID를 통해 request를 보낼 수 있지만, id값 만으로는 화면 구성에 어려움이 있어 보여 level을 응답에 담을 수 있도록 로직을 구현했습니다.~~
- 루트 카테고리를 도입해 상위 카테고리의 부모를 지정했습니다.
- <img width="320" alt="image" src="https://github.com/KakaoFunding/back-end/assets/88381563/15ae6dfc-450b-4c71-bdaf-7cc3ada6c2bf">
- QuryDsl 첫 사용이라 일부 미숙할 수 있으니, 확인 부탁드립니다.
- 아직 구체적인 예외상황이 예측되지 않아 테스트케이스가 촘촘하지 않습니다. 테스트 구체화가 필요해보이는 부분에 리뷰 부탁드립니다.
> Feature/12 카테고리 조회

- src/main/java/org/kakaoshare/backend/domain/option/dto/OptionDetailResponse.java
- src/main/java/org/kakaoshare/backend/domain/option/dto/OptionResponse.java
- src/main/java/org/kakaoshare/backend/domain/product/dto/DescriptionResponse.java
- src/main/java/org/kakaoshare/backend/domain/product/repository/query/ProductRepositoryCustomImpl.java
close #70 
상품 상세조회 쿼리 수정(OneToMany)관계 사라진 이후로 dto들을 통해 정적팩토리 메소드로 응답dto 생성
상품 상세조회 로직이 좀 변경이 많이 되긴했습니다.. onrToMany가 없다보니 getter도 못써서 부자연스럽게 보이긴 하는데 어떻게 다듬으면 좋을지 리뷰해주시면 감사할것 같습니다
> 상품상세 조회 쿼리수정

- src/main/java/org/kakaoshare/backend/domain/option/repository/OptionRepository.java
- src/main/java/org/kakaoshare/backend/domain/payment/dto/OrderDetail.java
- src/main/java/org/kakaoshare/backend/domain/payment/dto/ready/request/PaymentReadyProductDto.java
- src/main/java/org/kakaoshare/backend/domain/payment/dto/ready/request/PaymentReadyRequest.java
- src/main/java/org/kakaoshare/backend/domain/payment/exception/PaymentErrorCode.java
- src/main/java/org/kakaoshare/backend/domain/payment/service/KakaoPayRequestProvider.java
- src/main/java/org/kakaoshare/backend/domain/payment/service/PaymentService.java
- src/main/java/org/kakaoshare/backend/domain/payment/service/PaymentWebClientService.java
- src/main/java/org/kakaoshare/backend/domain/product/repository/query/ProductRepositoryCustom.java
- src/main/java/org/kakaoshare/backend/domain/product/repository/query/ProductRepositoryCustomImpl.java
- src/main/java/org/kakaoshare/backend/domain/receipt/entity/ReceiptOption.java
- src/test/java/org/kakaoshare/backend/domain/payment/service/PaymentServiceTest.java
- src/test/java/org/kakaoshare/backend/fixture/MemberFixture.java
close #81
- 결제 준비시 선택한 옵션 검증 추가
- 결제 준비시 결제 금액 검증 버그 수정
- 결제 준비시 프론트로부터 상품명을 전달 안 받도록 수정
- 결제 관련 DTO의 "수량"을 나타내는 필드명을 `stockQuantity` 에서 `quantity`로 수정
- 기타 오류 상황(e.g. 회원 인증X)마다 알맞는 예외를 발생시키도록 수정
- `ReceiptOption` 이 `BaseTimeEntity`를 상속받도록 수정
포스트맨 참고
결제 로직이 매우 복잡합니다! 이해안되는 부분있으시면 바로 물어봐주세요!
> 결제 관련 오류, ReceiptOption 엔티티 수정

- src/main/java/org/kakaoshare/backend/domain/funding/controller/FundingController.java
- src/main/java/org/kakaoshare/backend/domain/funding/dto/preview/request/FundingPreviewRequest.java
- src/main/java/org/kakaoshare/backend/domain/funding/dto/preview/request/FundingProductDto.java
- src/main/java/org/kakaoshare/backend/domain/funding/dto/preview/response/FundingPreviewAmount.java
- src/main/java/org/kakaoshare/backend/domain/funding/dto/preview/response/FundingPreviewResponse.java
- src/main/java/org/kakaoshare/backend/domain/funding/entity/Funding.java
- src/main/java/org/kakaoshare/backend/domain/funding/entity/FundingDetail.java
- src/main/java/org/kakaoshare/backend/domain/funding/exception/FundingErrorCode.java
- src/main/java/org/kakaoshare/backend/domain/funding/exception/FundingException.java
- src/main/java/org/kakaoshare/backend/domain/funding/repository/FundingDetailRepository.java
- src/main/java/org/kakaoshare/backend/domain/funding/repository/FundingRepository.java
- src/main/java/org/kakaoshare/backend/domain/funding/service/FundingService.java
- src/main/java/org/kakaoshare/backend/domain/gift/entity/Gift.java
- src/main/java/org/kakaoshare/backend/domain/order/entity/Order.java
- src/main/java/org/kakaoshare/backend/domain/payment/controller/PaymentController.java
- src/main/java/org/kakaoshare/backend/domain/payment/dto/FundingOrderDetail.java
- src/main/java/org/kakaoshare/backend/domain/payment/dto/ready/request/PaymentFundingReadyRequest.java
- src/main/java/org/kakaoshare/backend/domain/payment/service/PaymentService.java
- src/main/java/org/kakaoshare/backend/domain/product/repository/ProductRepository.java
- src/main/resources/db/migration/V4__modify_funding_detail_orders.sql
- src/main/resources/db/migration/V4__modify_gift.sql
- src/test/java/org/kakaoshare/backend/domain/payment/service/PaymentServiceTest.java
- src/test/java/org/kakaoshare/backend/fixture/FundingFixture.java
close #96 
- 펀딩 주문 페이지 로직 추가
- 펀딩 결제 로직 추가
- `Order` 엔티티 수정
- `FundingDetail` 연관관계 제거
- `FundingDetail` 엔티티 수정
- `Payment` 와 연관관계 추가
- `Member` 와 연관관계 추가
- `Funding` 인덱스 UNIQUE 속성 제거
- 포스트맨 참고
> 펀딩 결제 기능 추가

- src/main/java/org/kakaoshare/backend/domain/member/controller/RefreshTokenCookieProvider.java
close #115
- `RefreshTokenCookieProvider` 에 httpOnly, secure 옵션 활성화
> HOTFIX: Cookie 관련 httpOnly, secure 옵션 활성화

- src/main/java/org/kakaoshare/backend/domain/funding/dto/preview/request/FundingPreviewRequest.java
- src/main/java/org/kakaoshare/backend/domain/funding/dto/preview/request/FundingProductDto.java
- src/main/java/org/kakaoshare/backend/domain/funding/dto/preview/response/FundingPreviewAmount.java
- src/main/java/org/kakaoshare/backend/domain/funding/dto/preview/response/FundingPreviewResponse.java
- src/main/java/org/kakaoshare/backend/domain/funding/repository/FundingRepository.java
- src/main/java/org/kakaoshare/backend/domain/funding/service/FundingService.java
- src/main/java/org/kakaoshare/backend/domain/product/dto/Product4DisplayDto.java
- src/main/java/org/kakaoshare/backend/domain/product/dto/ProductDto.java
- src/main/java/org/kakaoshare/backend/domain/product/repository/ProductRepository.java
- src/main/java/org/kakaoshare/backend/domain/product/repository/query/ProductRepositoryCustomImpl.java
- src/test/java/org/kakaoshare/backend/domain/order/service/OrderServiceTest.java
close #166
- 펀딩 결제 페이지(`funding/preview`)
- 요청 Body에 기여 금액 제거
- 응답 Body에 상품 금액 추가
- 응답 Body에 브랜드명 추가
- `ProductDto` 에 `brandName` 필드 추가
> 펀딩 결제 페이지 요청/응답 Body 수정, ProductDto에 brandName 필드 추가

- src/main/java/org/kakaoshare/backend/domain/member/dto/oauth/authenticate/OAuthLoginMemberResponse.java
- src/main/java/org/kakaoshare/backend/domain/member/dto/oauth/profile/OAuthProfile.java
- src/main/java/org/kakaoshare/backend/domain/member/dto/oauth/profile/detail/KakaoProfile.java
> 로그인 시 프로필 사진, ID 추가

- src/main/java/org/kakaoshare/backend/common/config/SecurityConfig.java
토큰 재발급 URL 인증 권한을 제거
close #198
- 토큰 재발급 요청 URL에 `permitAll()` 적용
> [HOTFIX] api/v1/ouath/reissue URL을 permitAll()로 설정

- src/main/java/org/kakaoshare/backend/common/vo/Date.java
- src/main/java/org/kakaoshare/backend/domain/order/controller/OrderController.java
- src/main/java/org/kakaoshare/backend/domain/order/dto/inquiry/OrderHistoryRequest.java
- src/main/java/org/kakaoshare/backend/domain/order/repository/query/OrderRepositoryCustom.java
- src/main/java/org/kakaoshare/backend/domain/order/repository/query/OrderRepositoryCustomImpl.java
- src/main/java/org/kakaoshare/backend/domain/order/service/OrderService.java
- src/main/java/org/kakaoshare/backend/domain/order/vo/OrderHistoryDate.java
- src/test/java/org/kakaoshare/backend/domain/order/service/OrderServiceTest.java
close #196 
- `OrderService.lookUp()`, `OrderController.lookUp()` 시그니처 변경
- 별도의 요청 DTO(`OrderHistoryRequest`) 를 사용
- 파라미터에 `providerId` 추가
- `OrderRepositoryCustom.findAllOrderProductDtoByDate()` 수정
- 메서드명을 `findAllOrderProductDtoByCondition` 으로 변경
- 구현부 메서드 추출
- `providerId` 를 `where` 문에 추가
- 포스트맨 참고
> 주문내역 조회 로직 변경

- src/main/java/org/kakaoshare/backend/domain/brand/controller/BrandController.java
- src/main/java/org/kakaoshare/backend/domain/brand/repository/query/BrandRepositoryCustom.java
- src/main/java/org/kakaoshare/backend/domain/brand/repository/query/BrandRepositoryCustomImpl.java
- src/main/java/org/kakaoshare/backend/domain/brand/service/BrandService.java
- src/test/java/org/kakaoshare/backend/domain/brand/repository/BrandRepositoryTest.java
close #200 
카테고리 id로 브랜드 조회 (`api/v1/brands/{categoryId}`) API 응답값을 페이징 객체에서 `List`로 수정하였습니다.
- `brandController.getSimpleBrandsInfo()` 수정
- 파라미터에 `Pageable` 제거
- `brandService.getSimpleBrandPage()` 
- 반환타입을 `Page<?>`에서 `List<?>` 로 수정
- `brandRepository.findAllSimpleBrandByCategoryId()`
- 반환타입을 `Page<?>`에서 `List<?>` 로 수정
- 파라미터에 `Pageable` 제거
- 포스트맨 참고
예찬님께서 맡으신 로직을 수정한거라 이상한 부분도 있을겁니다! 피드백주시면 바로 반영하겠습니다!
> 카테고리 ID로 브랜드 조회 응답값을 페이징에서 리스트로 수정

- src/main/java/org/kakaoshare/backend/domain/gift/entity/FundingGift.java
DDL validate 시 enum 타입으로 간주되어 columnDefinition을 사용해 varchar로 명시
close #203
- `FundingGift`의 `status`필드에 `columnDefinition = VARCHAR(255)` 속성 추가
> [HOTFIX]FundingGift의 status 필드에 columnDefinition 속성 추가

- src/main/java/org/kakaoshare/backend/domain/product/dto/ProductSummaryResponse.java
- src/test/java/org/kakaoshare/backend/domain/payment/service/PaymentServiceTest.java
close #210 
- `ProductSummaryResponse`에 `price` 필드 추가
```java
public interface ProductRepository extends JpaRepository<Product, Long>, ProductRepositoryCustom {
@Query("SELECT NEW org.kakaoshare.backend.domain.product.dto.ProductSummaryResponse(p.brandName, p.photo, p.name, p.price) " +
"FROM Product p " +
"WHERE p.productId =:productId")
ProductSummaryResponse findAllProductSummaryById(@Param("productId") final Long productId);
}
```
위 `findAllProductSummaryById()` 메서드에서 `ProductSummaryResponse` 에 적절한 생성자가 없어서 오류가 발생했습니다. 알고보니 4번째 파라미터인 `p.price` 와 매칭되는 필드가 없었습니다. (다른 PR을 올리면서 누락된 것 같습니다.)
> [HOTFIX] 선물 결제 승인 오류 수정

- src/main/java/org/kakaoshare/backend/domain/member/dto/oauth/authenticate/OAuthLoginMemberResponse.java
- src/main/java/org/kakaoshare/backend/domain/member/dto/oauth/profile/OAuthProfile.java
- src/main/java/org/kakaoshare/backend/domain/member/dto/oauth/profile/detail/KakaoProfile.java
close #212
- `OAuthProfile` 에 `getBirthDate()` 추상 메서드 추가
- `KakaoProfile` 에 `getBirthDate()` 메서드 구현
- 카카오에선 사용자 생일 정보를 생년월일(YYYY), 생일(MMDD) 형식으로 제공하여 이를 적절히 파싱 [참고](https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#req-user-info-response)
- `OAuthLoginMemberResponse` 에 `birtDate` 필드 추가 및 정적 팩토리 메서드 수정
- 포스트맨 참고
> 로그인시 생년월일 응답값에 추가

- src/main/java/org/kakaoshare/backend/domain/funding/dto/inquiry/ContributedFundingHistoryDto.java
- src/main/java/org/kakaoshare/backend/domain/funding/repository/query/FundingDetailRepositoryCustomImpl.java
- src/test/java/org/kakaoshare/backend/domain/funding/service/FundingDetailServiceTest.java
close #221 
- `ContributedFundingHistoryDto` 에 `attributeAmount` 필드 추가
- 이에 영향받는 `FundingDetailServiceTest`, `FundingDetailRepositoryCustomImpl` 수정
> [HOTFIX] 기여한 펀딩내역 조회 응답값에 기여 금액 추가

- src/main/java/org/kakaoshare/backend/domain/friend/service/KakaoFriendService.java
- src/main/java/org/kakaoshare/backend/domain/funding/controller/FundingController.java
- src/main/java/org/kakaoshare/backend/domain/funding/dto/FriendFundingItemRequest.java
- src/main/java/org/kakaoshare/backend/domain/funding/dto/FundingResponse.java
- src/main/java/org/kakaoshare/backend/domain/funding/dto/ProgressResponse.java
- src/main/java/org/kakaoshare/backend/domain/funding/dto/inquiry/FundingContributorResponse.java
- src/main/java/org/kakaoshare/backend/domain/funding/entity/Funding.java
- src/main/java/org/kakaoshare/backend/domain/funding/repository/FundingDetailRepository.java
- src/main/java/org/kakaoshare/backend/domain/funding/repository/FundingRepository.java
- src/main/java/org/kakaoshare/backend/domain/funding/service/FundingDetailService.java
- src/main/java/org/kakaoshare/backend/domain/funding/service/FundingService.java
- src/main/java/org/kakaoshare/backend/domain/member/dto/oauth/profile/detail/KakaoFriendListDto.java
- src/main/java/org/kakaoshare/backend/domain/member/exception/MemberErrorCode.java
- src/main/java/org/kakaoshare/backend/domain/member/repository/MemberRepository.java
- src/main/java/org/kakaoshare/backend/domain/member/service/oauth/OAuthWebClientService.java
- src/test/java/org/kakaoshare/backend/domain/funding/service/FundingServiceTest.java
close #216 
- 펀딩 id를 기준으로 펀딩아이템 조회 기능 구현
- 친구들의 펀딩아이템 조회 기능 구현
- 펀딩 기여한 친구들의 랭킹구현은 아직 안됬습니다. 알바다녀와서 새벽에 작업하겠습니다.(기간이 얼마남지 않아 수정할 부분을 미리 지적받고 싶어 pr올립니다.)
내 진행중인 펀딩아이템 조회는 잘 되는것 같습니다. 하지만 이전 예찬님의 친구들의 위시목록 조회도 외부 api의 덕에 테스트 구현이 힘들었던걸로 기억하는데 mock을 처리해서 테스트를 할까 고민중에 있는데 그부분도 mocking을 하는데 시간이 오래걸릴것같습니다. 
친구들의 펀딩아이템 조회를 하고싶어도 프로젝트 developer에 제가 안들어가있어서 테스트를 해볼수가 없네요.. 이부분 저번에도 부탁드린것 같긴한데 확인 부탁드립니다.
> 진행중인 펀딩 아이템 조회

- src/main/java/org/kakaoshare/backend/domain/brand/repository/query/BrandRepositoryCustomImpl.java
close #232 
- `BrandRepositoryCustomImpl.findBySearchConditions()` 메서드 수정
- `brand`와 `product` 조인을 `leftJoin()`에서 `innerJoin`()으로 수정
- `groupBy(brandId)`를 통해 중복 데이터 제거
Brand(1)에서 Product(N)을 `LEFT JOIN` 후 `GROUP BY`를 하지 않아 발생한 문제였습니다. 
따라서, `GROUP BY` 절을 추가하여 중복 데이터를 제거했습니다.
추가로, 상품을 가지지 않는 브랜드를 고려하여 `LEFT JOIN`을 `INNER JOIN`으로 수정하였습니다.
```sql
SELECT b.brand_id, b.name, b.icon_photo FROM brand b
INNER JOIN product p on b.brand_id = p.brand_id
WHERE p.name LIKE '%커피%'
GROUP BY b.brand_id;
```
- 중복 데이터 (커피스미스)가 제거됨
> [HOTFIX] 검색 시 브랜드 중복 데이터 조회 문제 해결

- src/main/java/org/kakaoshare/backend/domain/funding/controller/FundingController.java
- src/main/java/org/kakaoshare/backend/domain/funding/repository/query/FundingRepositoryCustom.java
- src/main/java/org/kakaoshare/backend/domain/funding/repository/query/FundingRepositoryCustomImpl.java
- src/main/java/org/kakaoshare/backend/domain/funding/service/FundingService.java
- 커스텀된 응답 페이지로 반환 해주지 않아 반환타입이 다른점 수정
> [fix] 등록했던 펀딩아이템 조회 페이지 응답객체 타입 수정

- src/main/java/org/kakaoshare/backend/common/config/SecurityConfig.java
- src/main/java/org/kakaoshare/backend/common/error/handler/AuthenticationAccessDeniedHandler.java
- src/main/java/org/kakaoshare/backend/common/error/handler/CustomAuthenticationEntryPoint.java
- src/main/java/org/kakaoshare/backend/common/error/handler/GlobalExceptionHandler.java
- src/main/java/org/kakaoshare/backend/common/error/response/ErrorResponse.java
- src/main/java/org/kakaoshare/backend/common/filter/JwtAuthenticationFilter.java
- src/main/java/org/kakaoshare/backend/jwt/exception/JwtErrorCode.java
- src/main/java/org/kakaoshare/backend/jwt/exception/JwtException.java
close #239 
- PR #189 누락된 내용 추가
> [HOTFIX] PR #189 누락된 내용 추가

- src/main/java/org/kakaoshare/backend/domain/wish/entity/Wish.java
- src/main/java/org/kakaoshare/backend/domain/wish/repository/WishRepository.java
- src/main/java/org/kakaoshare/backend/domain/wish/service/WishService.java
close #243 
- `WishService.handleWishCancel()` 수정
- 이전 위시 삭제 로직은 DB에 저장되있는 위시 내역을 삭제하지 않고 삭제하려는 `Wish` 엔티티와 동일한 필드를 갖는 새로운 `Wish` 엔티티를 만들고 이를 삭제하는 방식이였습니다. (`createWish()` 호출 후 이를 삭제)
- `WishRepository.deleteByMemberAndProduct()` 를 추가하여 현재 삭제하려고 하는 위시 내역을 실제 DB에서 삭제하도록 수정했습니다.
- `Wish` 엔티티 `Member` 필드 Cascade 속성 삭제
- 포스트맨 참고
> 위시 삭제가 DB에 반영되지 않는 문제 해결

- src/main/java/org/kakaoshare/backend/domain/member/controller/OAuthController.java
- src/main/java/org/kakaoshare/backend/domain/member/dto/oauth/logout/OAuthSocialLogoutRequest.java
- src/main/java/org/kakaoshare/backend/domain/member/dto/oauth/logout/detail/kakao/request/KakaoLogoutRequest.java
- src/main/java/org/kakaoshare/backend/domain/member/service/oauth/OAuthService.java
- src/main/java/org/kakaoshare/backend/domain/member/service/oauth/OAuthWebClientService.java
- src/main/java/org/kakaoshare/backend/domain/member/service/oauth/detail/kakao/KakaoOAuthRequestProvider.java
- src/main/java/org/kakaoshare/backend/domain/member/service/oauth/detail/kakao/KakaoOAuthService.java
- src/main/resources/application-dev.yml
- src/test/java/org/kakaoshare/backend/domain/member/service/OAuthServiceTest.java
close #236
기존 로그아웃 시 서버에서 발급한 토큰만 만료가되고 소셜 토큰은 만료되지 않아 악용될 가능성이 있다고 판단했습니다. 따라서, 사용자가 로그아웃 시 소셜 토큰도 만료하는 로직을 추가하였습니다.
이 API는 사용자가 로그아웃을 요청할 때 기존 로그아웃 API(`api/v1/oauth/logout`)와 함께 호출됩니다. 사용자 로그아웃 과정은 아래와 같습니다.
1. 소셜 토큰 만료
2. 서버 토큰 만료
- `OAuthWebClientService` 계층화
- `OAuthWebClientService`를 인터페이스로 수정
- `KakaoOAuthService` 구현체 추가
- `OAuthWebClientService.expireToken()` 메서드 추가
- `KakaoOAuthRequestProvider` 클래스 추가
- 로그아웃 시 필요한 요청값을 만드는 클래스
- `application-dev.yml` 에 카카오 토큰 만료 URL 속성 추가
- `OAuthService`, `OAuthController` 에 `socialLogout()` 메서드 추가
포스트맨 참고
> 소셜 로그아웃 로직 추가 및 기존 OAuthWebClientService 계층화

- src/main/java/org/kakaoshare/backend/common/vo/Date.java
close #254 
- `Date` VO의 `endDate`가 `LocalDate.now()` 보다 이후인 경우만 검증하도록 수정
- `startDate`, `endDate` 둘 중 하나라도 `null` 이면 예외를 발생시키도록 수정
- 현재는 두 개 모두 `null`이여야 예외가 발생하도록 구현되있음
`LocalDate.isAfter()`가 같은날인 경우도 `false`를 반환하여 발생한 버그를 해결하였습니다.
> [HOTFIX]날짜 필터링 검증 버그 해결

- src/main/java/org/kakaoshare/backend/common/util/RepositoryUtils.java
- src/main/java/org/kakaoshare/backend/common/vo/date/Date.java
- src/main/java/org/kakaoshare/backend/common/vo/date/exception/DateErrorCode.java
- src/main/java/org/kakaoshare/backend/common/vo/date/exception/DateException.java
- src/main/java/org/kakaoshare/backend/domain/funding/repository/query/FundingDetailRepositoryCustom.java
- src/main/java/org/kakaoshare/backend/domain/funding/repository/query/FundingDetailRepositoryCustomImpl.java
- src/main/java/org/kakaoshare/backend/domain/funding/vo/FundingHistoryDate.java
- src/main/java/org/kakaoshare/backend/domain/order/vo/OrderHistoryDate.java
- src/test/java/org/kakaoshare/backend/domain/funding/service/FundingDetailServiceTest.java
- src/test/java/org/kakaoshare/backend/domain/order/service/OrderServiceTest.java
close #257 
- `DateException`, `DateErrorCode` 추가
- `Date.validateDateRange()` 커스텀 예외 추가
__조회 마감 기간이 미래인 경우__
__기간 범위가 잘못된 경우__
__기간이 없는 경우__
> [FEAT, REFACTOR] Date VO 예외 핸들링 추가

- src/main/java/org/kakaoshare/backend/domain/member/entity/Member.java
- src/main/java/org/kakaoshare/backend/domain/member/service/oauth/OAuthService.java
> [HOTFIX] 로그인시 중복 회원가입 오류 해결

- src/main/java/org/kakaoshare/backend/domain/funding/controller/FundingController.java
- src/main/java/org/kakaoshare/backend/domain/funding/dto/inquiry/FriendFundingInquiryRequest.java
- src/main/java/org/kakaoshare/backend/domain/funding/service/FundingService.java
close #286 
친구의 펀딩아이템 조회 시 fundingId를 클라이언트가 줘야하는 과정 삭제
> 친구의 펀딩아이템 조회시 불필요한 과정 삭제

- src/main/java/org/kakaoshare/backend/domain/funding/exception/FundingErrorCode.java
- src/main/java/org/kakaoshare/backend/domain/funding/service/FundingService.java
- src/test/java/org/kakaoshare/backend/domain/funding/service/FundingServiceTest.java
close #292 
- 펀딩 등록 시 예외검증 기능 추가
> 펀딩 등록 시 목표금액 검증 로직  추가

- src/main/java/org/kakaoshare/backend/domain/gift/repository/query/GiftRepositoryCustomImpl.java
- src/test/java/org/kakaoshare/backend/domain/gift/repository/GiftRepositoryTest.java
close #293 
- receipt 엔티티의 컬럼명 변경으로 인한 쿼리 수정
> [HOTFIX]선물함 조회 쿼리 수정

- src/main/java/org/kakaoshare/backend/domain/gift/dto/inquiry/history/GiftDto.java
- src/main/java/org/kakaoshare/backend/domain/gift/repository/query/GiftRepositoryCustomImpl.java
- src/main/java/org/kakaoshare/backend/domain/product/dto/ProductDto.java
- src/test/java/org/kakaoshare/backend/domain/gift/repository/GiftRepositoryTest.java
close #308 
- `GiftRepositoryCustomImpl.createHistoryBaseQuery()` 조인 대상 변경
- 보낸 이 (`Recipient`), 받는 이 (`Receiver`) 과 모두 Join하도록 수정
- 보낸이 : 응답값에 사용
- 받는이: `where`절에서 사용 
기존 선물내역 조회 SQL 문에서 Join 대상이 잘못되어 발생한 문제였습니다.
포스트맨 참고
> [HOTFIX] 선물 조회 시 보낸 이의 선물내역을 보여주는 현상 해결

- src/main/java/org/kakaoshare/backend/common/config/SecurityConfig.java
- src/main/java/org/kakaoshare/backend/logging/filter/LoggingFilter.java
close #315
- `LoggingFilter` 에 `/actuator`, `/favicon.ico` URL 요청에 대해 로깅하지 않도록 설정
- `/favicon.ico` 요청에 대해 `permitAll()` 설정
> [FEAT] metric 사용시 로깅을 사용하지 않는 로직 추가, favicon.ico 요청 허용

- src/main/java/org/kakaoshare/backend/domain/receipt/entity/ReceiptOption.java
close #320
- `ReceiptOption` 테이블이 `BaseTimeEnttiy`를 상속받도록 수정
> [HOTFIX]ReceiptOption 엔티티가 BaseTimeEntity를 상속받도록 수정

- src/main/java/org/kakaoshare/backend/domain/cart/dto/inquiry/CartResponse.java
장바구니 조회 요청시 체크 여부를 응답 객체에 추가
close #326 
- 장바구니 조회시 체크 여부를 응답객체에 추가
- 이를 통해 장바구니 체크 여부를 사용자가 확인 가능
- ![image](https://github.com/KakaoFunding/back-end/assets/88381563/9e7aa35d-834b-42d3-8054-4d4c84dbfb41) `selected` 필드 확인
> [fix]응답 객체 수정 (#326)
